version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      # - pip install --upgrade pip
      # - pip install --upgrade awscli aws-sam-cli
      - pip install jq
      # Enable docker https://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker-custom-image.html
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  build:
    commands:
      - cd "${PROJECT_SUBFOLDER}"
      - ls
      - cat parameters/prod-parameters.json
      - SAM_PARAMETERS=$( cat parameters/prod-parameters.json | jq -r '[ .[] | "\(.ParameterKey)=\(.ParameterValue)" ] | join(" ")' )
      - sam build   --use-container --template "template.yaml" --parameter-overrides $SAM_PARAMETERS
      - . pipeline/assume-role.sh "${PROD_PIPELINE_EXECUTION_ROLE}" prod-package
      - sam package --config-file pipeline/samconfig-pipeline.toml 
                    --config-env "${PROD_ENV_CONFIG_NAME}"
                    --output-template-file "packaged-prod.yaml"

artifacts:
  files:
    - '**/*'